package userGUIcomponent;

import EmpowerVoteClient.LanguageManager;
/**
 * DefaultPanel class provides a welcome message and instructions for users
 * on how to navigate the voting system.
 */
public class DefaultPanel extends javax.swing.JPanel implements LanguageManager.LanguageChangeListener {

    // Variables declaration
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;

    public DefaultPanel() {
        initComponents();
        LanguageManager.getInstance().addListener(this); // Register for language updates
        updateText(LanguageManager.getInstance().getLanguageIndex()); // Set initial text
    } // End constructor

    private void updateText(int languageIndex) {
        // Language-specific translations
        String[][] texts = {
            // English
            {
                "Welcome to EmpowerVote!",
                "Select any elections you would like to vote in using the menu on the left",
                "When you have made all of your selections",
                "Go to review and submit to complete your ballot!"
            },
            // Spanish
            {
                "¡Bienvenido a EmpowerVote!",
                "Seleccione las elecciones en las que desea votar utilizando el menú de la izquierda",
                "Cuando haya hecho todas sus selecciones",
                "Vaya a revisar y enviar para completar su boleta"
            },
            // Russian
            {
                "Добро пожаловать в EmpowerVote!",
                "Выберите выборы, в которых хотите участвовать, используя меню слева",
                "Когда вы сделаете все свои выборы",
                "Перейдите к проверке и отправке, чтобы завершить ваш бюллетень"
            }
        };

        jLabel1.setText(texts[languageIndex][0]);
        jLabel2.setText(texts[languageIndex][1]);
        jLabel3.setText(texts[languageIndex][2]);
        jLabel4.setText(texts[languageIndex][3]);
    }

    @Override
    public void onLanguageChange(int newIndex) {
        updateText(newIndex);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to EmpowerVote!");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Select any elections you would like to vote in using the menu on the left");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("When you have made all of your selections");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("go to review and submit to complete your ballot!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 202, Short.MAX_VALUE))
        );
    } // End initComponents
} // End DefaultPanel
